# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    before_deploy:
    - R CMD INSTALL .
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      skip_cleanup: true
  - r: release
    pandoc: false
    env: PANDOC='none'
  - r: release
    os: osx
    osx_image: xcode7.3 # CRAN: El Capitan
    pandoc: false
    before_install:
      - curl -fLo /tmp/pandoc-1.12-1.dmg https://github.com/jgm/pandoc/releases/download/1.12/pandoc-1.12-1.dmg
      - sudo hdiutil attach /tmp/pandoc-1.12-1.dmg -mountpoint /Volumes/pandoc
      - sudo installer -pkg "/Volumes/pandoc/pandoc-1.12.pkg" -allowUntrusted -target /
      - sudo hdiutil detach /Volumes/pandoc
    env: PANDOC='mac-cran'
  - r: oldrel
  - r: 3.3
  - r: 3.2
  - r: 3.1

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE
